apiVersion: v1
kind: Secret
metadata:
  name: gearup-secrets
  namespace: gearup
type: Opaque
stringData:
  # PostgreSQL Database Configuration
  # Replace with your actual database connection details
  spring-datasource-url: jdbc:postgresql://YOUR_DB_HOST:5432/YOUR_DB_NAME?sslmode=require
  spring-datasource-username: YOUR_DB_USERNAME
  spring-datasource-password: YOUR_DB_PASSWORD
  
  # JWT Secret
  # Generate a strong secret key for JWT token signing
  jwt-secret: YOUR_BASE64_ENCODED_JWT_SECRET_KEY
  
  # Email credentials
  # Replace with your SMTP email credentials
  mail-username: your-email@gmail.com
  mail-password: YOUR_APP_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: gearup
type: Opaque
stringData:
  # Redis password (leave empty if Redis has no password)
  redis-password: ""
